### ISSUE TITLE
Hibernate Persistence issue with BOGO offer

### ISSUE THREAD

**Issue by phillipuniverse** [BroadleafCommerce/LegacyDemoSite#10]
When a (unauthenticated) user adds at least 2 items in a cart and selects multiship selection from the checkout page, then adding the first address works fine, but adding the second address(for the second item) causes hibernate errors.
Works fine if user is logged in.

![image](https://f.cloud.github.com/assets/684275/614689/098919a6-ce23-11e2-8878-4b2d321c4961.png)

``` console
[artifact:mvn] org.springframework.dao.DataIntegrityViolationException: Could not execute JDBC batch update; SQL [delete from BLC_ADDRESS where ADDRESS_ID=?]; constraint [FKC5B9EF18C13085DD]; nested exception is org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
[artifact:mvn] at org.springframework.orm.hibernate3.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:643)
[artifact:mvn] at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:104)
[artifact:mvn] at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:516)
[artifact:mvn] at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:754)
[artifact:mvn] at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:723)
[artifact:mvn] at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:392)
[artifact:mvn] at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:120)
[artifact:mvn] at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
[artifact:mvn] at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:90)
[artifact:mvn] at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
[artifact:mvn] at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
[artifact:mvn] at $Proxy109.saveCustomerAddress(Unknown Source)
[artifact:mvn] at org.broadleafcommerce.core.web.controller.checkout.BroadleafCheckoutController.saveMultishipAddAddress(BroadleafCheckoutController.java:298)
[artifact:mvn] at com.mycompany.controller.checkout.CheckoutController.saveMultishipAddAddress(CheckoutController.java:113)
[artifact:mvn] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[artifact:mvn] Caused by: 
[artifact:mvn] org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
[artifact:mvn] at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:96)
[artifact:mvn] at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:66)
[artifact:mvn] at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:275)
[artifact:mvn] at org.hibernate.engine.Action
..
[artifact:mvn] java.sql.BatchUpdateException: integrity constraint violation: foreign key no action; FKC5B9EF18C13085DD table: BLC_FULFILLMENT_GROUP
[artifact:mvn] at org.hsqldb.jdbc.JDBCPreparedStatement.executeBatch(Unknown Source)
[artifact:mvn] at org.apache.commons.dbcp.DelegatingStatement.executeBatch(DelegatingStatement.java:297)
[artifact:mvn] at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:70)
[artifact:mvn] at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:268)
[artifact:mvn] at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:268)
[artifact:mvn] at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:189)
[artifact:mvn] at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:321)
[artifact:mvn] at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:51)
[artifact:mvn] at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1216)
[artifact:mvn] at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:383)
[artifact:mvn] at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:133)
[artifact:mvn] at org.hibernate.ejb.TransactionImpl.commit(TransactionImpl.java:76)
[artifact:mvn] at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:512)
[artifact:mvn] at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:754)
[artifact:mvn] at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:723)
[artifact:mvn] at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:392)
[artifact:mvn] at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:120)
[artifact:mvn] at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
[artifact:mvn] at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:90)
[artifact:mvn] at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
[artifact:mvn] at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
[artifact:mvn] at $Proxy109.saveCustomerAddress(Unknown Source)
[artifact:mvn] at org.broadleafcommerce.core.web.controller.checkout.BroadleafCheckoutController.saveMultishipAddAddress(BroadleafCheckoutController.java:298)
[artifact:mvn] at com.mycompany.controller.checkout.CheckoutController.saveMultishipAddAddress(CheckoutController.java:113)
[artifact:mvn] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[artifact:mvn] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
...
[artifact:mvn] at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:603)
[artifact:mvn] at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:538)
[artifact:mvn] at java.lang.Thread.run(Thread.java:680)
[artifact:mvn] [ WARN] 11:43:54 JDBCExceptionReporter - SQL Error: -8, SQLState: 23504
[artifact:mvn] [ERROR] 11:43:54 JDBCExceptionReporter - integrity constraint violation: foreign key no action; FKC5B9EF18C13085DD table: BLC_FULFILLMENT_GROUP
```

Originally opened by @priyeshgpatel

**Comment by phillipuniverse** [comment]
This has been resolved by https://github.com/BroadleafCommerce/BroadleafCommerce/pull/365
