### ISSUE TITLE
Error while running jetty-demo task for the site

### ISSUE THREAD

**Issue by ashihaby** [BroadleafCommerce/LegacyDemoSite#133]
I have followed the get started guide for running the site, but I have received this error. 

```
[artifact:mvn] 2014-06-07 06:39:09.566:WARN:oejw.WebAppContext:Failed startup of context o.m.j.p.JettyWebAppContext{/,file:/home/amal/CloudCommerce/eclipse-workspace/DemoSite/site/target/mycompany/},file:/home/amal/CloudCommerce/eclipse-workspace/DemoSite/site/target/mycompany/
[artifact:mvn] java.io.EOFException
[artifact:mvn]  at java.util.zip.ZipInputStream.readFully(ZipInputStream.java:426)
[artifact:mvn]  at java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:295)
[artifact:mvn]  at java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:121)
[artifact:mvn]  at java.util.jar.JarInputStream.getNextEntry(JarInputStream.java:142)
[artifact:mvn]  at java.util.jar.JarInputStream.getNextJarEntry(JarInputStream.java:179)
[artifact:mvn]  at org.eclipse.jetty.webapp.JarScanner.matched(JarScanner.java:156)
[artifact:mvn]  at org.eclipse.jetty.util.PatternMatcher.matchPatterns(PatternMatcher.java:94)
[artifact:mvn]  at org.eclipse.jetty.util.PatternMatcher.match(PatternMatcher.java:76)
[artifact:mvn]  at org.eclipse.jetty.webapp.JarScanner.scan(JarScanner.java:78)
[artifact:mvn]  at org.eclipse.jetty.webapp.MetaInfConfiguration.preConfigure(MetaInfConfiguration.java:78)
[artifact:mvn]  at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:438)
[artifact:mvn]  at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:474)
[artifact:mvn]  at org.mortbay.jetty.plugin.JettyWebAppContext.doStart(JettyWebAppContext.java:256)
[artifact:mvn]  at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
[artifact:mvn]  at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:224)
[artifact:mvn]  at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:167)
[artifact:mvn]  at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
[artifact:mvn]  at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:224)
[artifact:mvn]  at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
[artifact:mvn]  at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
[artifact:mvn]  at org.eclipse.jetty.server.Server.doStart(Server.java:272)
[artifact:mvn]  at org.mortbay.jetty.plugin.JettyServer.doStart(JettyServer.java:65)
[artifact:mvn]  at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
[artifact:mvn]  at org.mortbay.jetty.plugin.AbstractJettyMojo.startJetty(AbstractJettyMojo.java:511)
[artifact:mvn]  at org.mortbay.jetty.plugin.AbstractJettyMojo.execute(AbstractJettyMojo.java:364)
[artifact:mvn]  at org.mortbay.jetty.plugin.JettyRunMojo.execute(JettyRunMojo.java:516)
[artifact:mvn]  at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
[artifact:mvn]  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[artifact:mvn]  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[artifact:mvn]  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[artifact:mvn]  at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
[artifact:mvn]  at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
[artifact:mvn]  at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[artifact:mvn]  at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
[artifact:mvn]  at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
[artifact:mvn]  at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
[artifact:mvn]  at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
[artifact:mvn]  at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
[artifact:mvn]  at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
[artifact:mvn]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[artifact:mvn]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[artifact:mvn]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[artifact:mvn]  at java.lang.reflect.Method.invoke(Method.java:606)
[artifact:mvn]  at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[artifact:mvn]  at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[artifact:mvn]  at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[artifact:mvn]  at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[artifact:mvn]  at org.codehaus.classworlds.Launcher.main(Launcher.java:46)
[artifact:mvn] 2014-06-07 06:39:09.589:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:8080
```

If you have any idea about this error, please let me know. 
Thanks,

**Comment by bpolster** [comment]
This question is more appropriate for the forums.
