### ISSUE TITLE
Order confirmation email not sent during guest checkout

### ISSUE THREAD

**Issue by tduffey** [BroadleafCommerce/LegacyDemoSite#16]
Order confirmation emails are not sent during guest checkout because the guest customer does not have its email address populated and therefore the retrieve by email address on line 61 of OrderConfirmationController returns null.

We hacked this by using order.getCustomer() rather than customerDao.readCustomerByEmail() and then setting the guest customer's email address, first name and last name from the order's first payment info. Not sure if this is the best solution but it does result in the order confirmation email getting sent.

**Comment by mausumi345** [comment]
Order confirmation mail is not being send though i am using a  registered user.Exception processing template "orderConfirmation-email": Exception evaluating SpringEL expression:
org.springframework.mail.MailPreparationException: Could not prepare mail; nested exception is org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating SpringEL expression: "customer.username" (orderConfirmation-email:6)
    at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:367)
    at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:344)
    at org.broadleafcommerce.common.email.service.message.MessageCreator.sendMessage(MessageCreator.java:40)
    at org.broadleafcommerce.common.email.service.EmailServiceImpl.sendBasicEmail(EmailServiceImpl.java:96)
    at org.broadleafcommerce.common.email.service.EmailServiceImpl.sendTemplateEmail(EmailServiceImpl.java:66)
    at org.broadleafcommerce.common.email.service.EmailServiceImpl.sendTemplateEmail(EmailServiceImpl.java:73)
    at com.evotec.mlsmr.controller.checkout.MyEmailServiceImpl.sendOrderConfirmation(MyEmailServiceImpl.java:31)
    at com.evotec.mlsmr.service.checkout.workflow.MyCompleteOrderActivity.execute(MyCompleteOrderActivity.java:22)
    at org.broadleafcommerce.core.checkout.service.workflow.CompleteOrderActivity.execute(CompleteOrderActivity.java:26)
    at org.broadleafcommerce.core.workflow.SequenceProcessor.doActivities(SequenceProcessor.java:79)
    at org.broadleafcommerce.core.checkout.service.CheckoutServiceImpl.performCheckout(CheckoutServiceImpl.java:72)
    at org.broadleafcommerce.core.web.controller.checkout.BroadleafCheckoutController.completeSecureCreditCardCheckout(BroadleafCheckoutController.java:416)
    at com.evotec.mlsmr.controller.checkout.CheckoutController.completeSecureCreditCardCheckout(CheckoutController.java:140)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
