### ISSUE TITLE
statement execution error and 404 after migration to mysql

### ISSUE THREAD

**Issue by SwEngin** [BroadleafCommerce/LegacyDemoSite#171]
After migrating to my sql I got the following and 404 when I try to run the site

```
[artifact:mvn] org.hibernate.tool.hbm2ddl.ImportScriptException: Error during statement execution (file: '/sql/load_i18n_countries.sql'): INSERT INTO BLC_ISO_COUNTRY (ALPHA_2, NAME, ALPHA_3, NUMERIC_CODE, STATUS) VALUES ('AX', '???land Islands', 'ALA', '248', 'OFFICIALLY_ASSIGNED')
[artifact:mvn]    at org.hibernate.tool.hbm2ddl.SchemaExport.importScript(SchemaExport.java:451)
[artifact:mvn]    at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:378)
[artifact:mvn]    at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:304)
[artifact:mvn]    at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:293)
[artifact:mvn]    at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:498)
[artifact:mvn]    at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1742)
[artifact:mvn]    at org.hibernate.ejb.EntityManagerFactoryImpl.<init>(EntityManagerFactoryImpl.java:94)
[artifact:mvn]    at org.hibernate.ejb.Ejb3Configuration.buildEntityManagerFactory(Ejb3Configuration.java:905)
[artifact:mvn]    at org.hibernate.ejb.Ejb3Configuration.buildEntityManagerFactory(Ejb3Configuration.java:890)
[artifact:mvn]    at org.springframework.orm.jpa.vendor.SpringHibernateEjbPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateEjbPersistenceProvider.java:51)
[artifact:mvn]    at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:343)
[artifact:mvn]    at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:318)
[artifact:mvn]    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1633)
[artifact:mvn]    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570)
[artifact:mvn]    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
[artifact:mvn]    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
[artifact:mvn]    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
[artifact:mvn]    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
[artifact:mvn]    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
[artifact:mvn]    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
[artifact:mvn]    at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:956)
[artifact:mvn]    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:747)
[artifact:mvn]    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
[artifact:mvn]    at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:403)
[artifact:mvn]    at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
[artifact:mvn]    at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
[artifact:mvn]    at org.broadleafcommerce.common.web.extensibility.MergeContextLoader.contextInitialized(MergeContextLoader.java:148)
[artifact:mvn]    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4939)
[artifact:mvn]    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5434)
[artifact:mvn]    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
[artifact:mvn]    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
[artifact:mvn]    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
[artifact:mvn]    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[artifact:mvn]    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[artifact:mvn]    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[artifact:mvn]    at java.lang.Thread.run(Thread.java:745)
[artifact:mvn] Caused by: java.sql.SQLException: Incorrect string value: '\xEF\xBF\xBD\xEF\xBF\xBD...' for column 'NAME' at row 1
[artifact:mvn]    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:998)
[artifact:mvn]    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
[artifact:mvn]    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
[artifact:mvn]    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
[artifact:mvn]    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
[artifact:mvn]    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2531)
[artifact:mvn]    at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1618)
[artifact:mvn]    at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1549)
[artifact:mvn]    at org.hibernate.tool.hbm2ddl.DatabaseExporter.export(DatabaseExporter.java:64)
[artifact:mvn]    at org.hibernate.tool.hbm2ddl.SchemaExport.importScript(SchemaExport.java:446)
[artifact:mvn]    ... 35 more
```

**Comment by bpolster** [comment]
Check the file mentioned in the error above.    From the looks of the message, it could be corrupt.

Here are the first couple of rows that should be in that file ..

```
-- ISO-3166-1 list of countries
-- see http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2 decoding table

INSERT INTO BLC_ISO_COUNTRY (ALPHA_2, NAME, ALPHA_3, NUMERIC_CODE, STATUS) VALUES ('AA', NULL, NULL, -1, 'USER_ASSIGNED');
```

**Comment by SwEngin** [comment]
The file is ok and runs ok as long as I use HSQLDB but when I switch to mysql I get this 
I even tried to import the sql file manually in mysql workbench and there was no problem. I'm on linux mint and hibernate connection character encoding and charset are set to utf-8 and use unicode is set to true

**Comment by bpolster** [comment]
Not sure what is going on there.   We use mysql almost exclusively and haven't observed this issue with enterprise which loads the same file.    I'd suggest opening a discussion item in the forums.
