### ISSUE TITLE
Name [jdbc/web] is not bound in this Context. Unable to find [jdbc]

### ISSUE THREAD

**Issue by bootups** [BroadleafCommerce/LegacyDemoSite#179]
When starting up the DemoSite (from Master) from Intellij getting the following exception. I have done some googling it appears to be a common issue, but no one has answered with a solution yet. Tried Tomcat 8.0.26 and Tomcat 7.0.33. Any ideas?

Caused by: javax.naming.NameNotFoundException: Name [jdbc/web] is not bound in this Context. Unable to find [jdbc].
    at org.apache.naming.NamingContext.lookup(NamingContext.java:818)
    at org.apache.naming.NamingContext.lookup(NamingContext.java:166)
    at org.apache.naming.SelectorContext.lookup(SelectorContext.java:157)
    at javax.naming.InitialContext.lookup(InitialContext.java:417)
    at org.springframework.jndi.JndiTemplate$1.doInContext(JndiTemplate.java:155)
    at org.springframework.jndi.JndiTemplate.execute(JndiTemplate.java:87)
    at org.springframework.jndi.JndiTemplate.lookup(JndiTemplate.java:152)
    at org.springframework.jndi.JndiTemplate.lookup(JndiTemplate.java:179)
    at org.springframework.jndi.JndiLocatorSupport.lookup(JndiLocatorSupport.java:104)
    at org.springframework.jndi.JndiObjectLocator.lookup(JndiObjectLocator.java:106)
    at org.springframework.jndi.JndiObjectFactoryBean.lookupWithFallback(JndiObjectFactoryBean.java:231)
    at org.springframework.jndi.JndiObjectFactoryBean.afterPropertiesSet(JndiObjectFactoryBean.java:217)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1633)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570)

**Comment by bootups** [comment]
Some more info: There is the same issue on an earlier post. I followed the instructions in this post:

1) Clone DemoSite repo
2) Open up DemoSite/build.properties and set proper path for maven.home
3) Run mvn clean install within DemoSite/
4) Navigate to DemoSite/site/ and run ant tomcat

I can run it from the command line. The problem occurs when I try and run it from IntelliJ. I am on MacOS X.

**Comment by kuntsevichalex** [comment]
I have exactly the same problem.
Can it be resolved somehow?

**Comment by kunzewitzalex** [comment]
I solved the same problem by adding a mysql-connector .jar file to the tomcat lib folder.

**Comment by disano357** [comment]
I had similar issue with tomcat 7, you should check if the lib folder of your tomcat installation contains tomcat-jdbc.jar
In my case it did not. You should also check the log of your tomcat installation for clues.
