### ISSUE TITLE
Context initialization failed

### ISSUE THREAD

**Issue by hugolam008** [BroadleafCommerce/LegacyDemoSite#208]
When starting up the DemoSite from Intellij getting the following exception. 

[ERROR] 17:07:22 ContextLoader - Context initialization failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'blCacheManager' defined in resource loaded from byte array: Invocation of init method failed; nested exception is net.sf.ehcache.CacheException: java.io.IOException: 拒绝访问。

at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)

at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
	
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)

I followed the instructions in adrianb11's post:

Clone DemoSite repo
Open up DemoSite/build.properties and set proper path for maven.home
Run mvn clean install within DemoSite/
Navigate to DemoSite/site/ and run ant tomcat
I can run it from the command line. The problem occurs when I try and run it from IntelliJ.

Any ideas?

**Comment by phillipuniverse** [comment]
@hugolam008 can you verify on our new starting point at https://github.com/BroadleafCommerce/CommunityDemo? It might be as simple as not having UTF-8 characters in your ehcache.xml.
